### ISSUE TITLE
Map DELFI attributes and values to OSM tags and values

### ISSUE THREAD

**Issue by Robbendebiene** [OPENER-next/OPENER-next#10]
DELFI to OSM:
  - https://wiki.openstreetmap.org/wiki/User:NVBWSeifert/Barrierefreie_Reisekette
  - https://wiki.openstreetmap.org/wiki/User:OPENER/DELFI_OSM_Tags

Tagging Mailingliste https://wiki.openstreetmap.org/wiki/Tagging_mailing_list

**Comment by 7h30n3** [comment]
An overview of the DELFI attributes can be found here: https://www.delfi.de/media/delfi_handbuch_barrierefreie_reiseketten_1._auflage_mai_2018.pdf
Beginning at page 197.

And all OSM tags can be found here: https://taginfo.openstreetmap.org/keys

**Comment by Robbendebiene** [comment]
This task is done.

The DELFI attribute to OSM tag mapping can be found here: https://wiki.openstreetmap.org/wiki/User:OPENER/DELFI_OSM_Tags
