### ISSUE TITLE
Style app

### ISSUE THREAD

**Issue by Robbendebiene** [OPENER-next/OPENER-next#15]
For visually impaired users or when app is used at night.

Make use of the system-wide setting for dark mode.
The high contrast theme should also be automatically activated if the user enabled this as a system-wide setting.

Use a barebone theme defining sizes etc. and let copies of that handle colors for light and dark theme

- [x] Create light theme
- [x] Create dark theme
- [x] Create high contrast theme
- [ ] Create graphics (e.g. for onboarding screen)

**Comment by 7h30n3** [comment]
Functionality was added in 20e3ee1. Now it's all about styling.
