### ISSUE TITLE
Choose/ Create Map Tile Styles (and Setup Tile Server)

### ISSUE THREAD

**Issue by 7h30n3** [OPENER-next/OPENER-next#38]
Choose or create suitable Map Tile Styles to help the user orientating on the map, e.g. by highlighting bus stop / lines.

Setup an own Tile Server.

**Comment by Robbendebiene** [comment]
We are now using tiles provided by [Thunderforest](https://www.thunderforest.com/).  (https://github.com/OPENER-next/OPENER-next/commit/5d71b14982e01edecbaf58c3f692dd70a9f15106)
Big thanks to @gravitystorm for the permission/extended quota.
